import numpy as np
import cupy as cp
import scipy.io
import sys

# from functions.fresnel_propagation_poly import fresnel_propagation_poly
from functions.fresnel_propagation_poly_v2 import fresnel_propagation_poly
from scipy.interpolate import CubicSpline, interp1d
from scipy.interpolate import RegularGridInterpolator as RGI
from functions.gpu_memory import gpu_memory

def fresnel_propagation_in_sample(Wi, lambda_, FOV, dz, phant_used, propa_type, dim, gpu_flag, logger, batch_size = 2):

    if dim == '1D':
        raise Exception('1D mode is not supported in projection_approximation.py')
    
    elif dim == '2D':
        nP_x = np.size(Wi, axis=1)
        nP_y = np.size(Wi, axis=2)
        dx = FOV / nP_x
        dy = FOV / nP_y

        fx = np.linspace(-0.5 / dx, 0.5 / dx, nP_x)
        fy = np.linspace(-0.5 / dy, 0.5 / dy, nP_y)
        FX, FY = np.meshgrid(fx, fy, indexing='ij')  # shape (nP_x, nP_y)

        Wo = np.zeros_like(Wi, dtype=np.complex128)
        nE = lambda_.shape[1]
        for i in range(0, nE, batch_size):
            i_end = min(i + batch_size, nE)
            lambda_batch = lambda_[0, i:i_end].reshape(-1, 1, 1)  # shape (b,1,1)
        
            if gpu_flag:
                dz =  cp.asarray(dz)
                lambda_batch = cp.asarray(lambda_batch)
                FX_cp = cp.asarray(FX)
                FY_cp = cp.asarray(FY)
                
                H = cp.exp(-1j * cp.pi * lambda_batch * (FX_cp**2 + FY_cp**2) * dz + 1j * 2 * cp.pi / lambda_batch * dz)
                del FX_cp, FY_cp
                H = cp.fft.fftshift(H, axes=(1, 2))

                Wi_cp = cp.asarray(Wi[i:i_end, :, :])
                phant_used_cp = cp.asarray(phant_used[i:i_end, :, :])
                Wi_cp = cp.multiply(Wi_cp, cp.exp(cp.multiply(-1j*2*cp.pi/lambda_batch, phant_used_cp)))
                del lambda_batch, phant_used_cp

                FWi = cp.fft.fftn(Wi_cp, axes=(1, 2))
                del Wi_cp
                FWo = cp.multiply(FWi, H)
                del FWi, H

                Wo_batch = cp.fft.ifftn(FWo, axes=(1, 2))
                del FWo
                Wo[i:i_end, :, :] = cp.asnumpy(Wo_batch)

                gpu_memory(f'projection_approximation Propagation {i_end/nE*100:.1f}%', logger)
                del Wo_batch
                cp._default_memory_pool.free_all_blocks()

            else:
                H = np.exp(-1j * np.pi * lambda_batch * (FX**2 + FY**2) * dz + 1j * 2 * np.pi / lambda_batch * dz)
                H = np.fft.fftshift(H, axes=(1, 2))

                Wi_batch = np.multiply(Wi[i:i_end, :, :], np.exp(np.multiply(-1j*2*np.pi/lambda_batch, phant_used[i:i_end, :, :])))
                FWi = np.fft.fftn(Wi_batch, axes=(1, 2))
                FWo = np.multiply(FWi, H)
                del FWi, H

                Wo_batch = np.fft.ifftn(FWo, axes=(1, 2))
                del FWo
                Wo[i:i_end, :, :] = Wo_batch
    
    return Wo

def projection_approximation(Wi, E, FOV, L, D, type_, d_s2, phant, n_slice, propa_type, dim, gpu_flag, logger, configs):
    '''
        DESCRIPTION:
            This function simulates the propagation of a wavefront through a grating-based X-ray imaging system using the projection approximation.
            It can handle both 1D and 2D modes, with the option to use GPU acceleration.
            The sphere phantom can be generated by the script "phantom//Sphere_3D_v2.py"
        
        CALL:
            - Wi: input wavefront, DIM 2 spatial dimension, DIM 1 energy dimension
            - E: vector containing energy range
            - FOV: target field of view (since the FOV will change in differentslices), unit: m
            - L: distance between G0 and G1, unit: m
            - D: distance between G1 and G2, unit: m
            - d_s2: the distance between g2 and sample (the side close to g2),unit: m
            - phant: a struct, containing a slice of the phantom and the material of the phantom and the voxel size of the phantom. The phantom matrix is a binary matrix. The phantom should be located between G1 and G2. If no phant exists, use [] as input.
            - n_slice: number of slices, which is different from "multi_slice_propagation_mod3". This is equivalent to different thicknesses.
            - propa_type: propagation type.
            - gpu_flag: logical variable whether using the GPU or not.
        OUTPUT:
            - Wo: output wavefront
        
        Updates:
        2025/06/01 (Longchao Men): optimize the GPU memory usage
        2024/10/28 (Longchao Men): first version
    '''
    phant_total = phant.phantom # shape: (n_slice, nP_x, nP_y)
    nP_x, nP_y = np.size(phant_total, axis=1), np.size(phant_total, axis=2)
    phant_total = np.expand_dims(phant_total, axis = 1) # shape: (n_slice, 1, nP_x, nP_y)

    n_slice = int(np.round(n_slice))
    if phant.gap == 0:
        z_sample = phant.slice_thickness*n_slice
    else:
        z_sample = phant.slice_thickness*n_slice + phant.gap*(n_slice-1)

    if not isinstance(E, np.ndarray):
        E = np.array([E]).reshape(1,-1)
    lambda_ = np.multiply(np.divide(1.239842, E), 1e-09).reshape(1,-1) # shape: (1, nE)

    ## load refractive index corresponding to the energy and fill the phantom with the refractive index
    mat_file = './/XOPDATA//' + phant.material + 'Data.mat'
    MatData_file = scipy.io.loadmat(mat_file)
    MatData = MatData_file['MatData']
    sc = CubicSpline(MatData[:,0], MatData[:,1])
    delta = np.reshape(sc(E*1000), (1,-1)) # shape: (1, nE)
    sc = CubicSpline(MatData[:,0], MatData[:,3])
    beta = np.reshape(np.multiply(sc(E*1000), 100), (1,-1)) * lambda_/(4*np.pi) # shape: (1, nE) 
    # delta - i beta 
    complex_refractive_index_term = delta - 1j * beta
    complex_refractive_index_term = np.expand_dims(np.transpose(complex_refractive_index_term), axis=2) # shape: (nE, 1, 1)
    
    if dim == '1D': 
        raise Exception('1D mode is not supported in projection_approximation.py')
    
    elif dim == '2D':
        dz = phant.slice_thickness
        ## planewave
        if type_ == 'planewave':
            ## propagate before the sample
            if propa_type == 'fresnel' or propa_type == 'quasi-projection':
                Wo_mid = fresnel_propagation_poly(Wi, E, FOV, L, D-z_sample-d_s2, 'planewave', dim, gpu_flag, logger)
            
            ## propagate inside the sample
            for ii in np.arange(0, n_slice-1):
                phant_used = np.multiply(phant_total[ii], complex_refractive_index_term) * phant.dx
                Wo_mid = fresnel_propagation_in_sample(Wo_mid, lambda_, FOV, dz, phant_used, propa_type, dim, gpu_flag, logger) # already consider the slice thickness
                # propagate gap between slices
                if phant.gap != 0: 
                    Wo_mid = fresnel_propagation_poly(Wo_mid, E, FOV, D-z_sample-d_s2+(ii)*phant.gap, phant.gap, 'planewave', dim, gpu_flag, logger)
    
                print("\r", end="")
                print("projection_approximation: {}% ".format(round((ii+1)/(n_slice-1)*100), 2), end="")
                sys.stdout.flush()

            phant_used = np.multiply(phant_total[-1], complex_refractive_index_term) * phant.dx
            Wo_mid = fresnel_propagation_in_sample(Wo_mid, lambda_, FOV, dz, phant_used, propa_type, dim, gpu_flag, logger) 
            if n_slice == 1:
                print("projection_approximation: 100% (just one slice)")

            ## propagate outside the sample
            if propa_type == 'fresnel' or propa_type == 'quasi-projection':
                Wo = fresnel_propagation_poly(Wo_mid, E, FOV, L+D-d_s2, d_s2, 'planewave', dim, gpu_flag, logger)

        ## pointsource 需要再写
        elif type_ == 'pointsource':
            raise Exception('pointsource mode is not supported in projection_approximation.py')
    
    return Wo